# Generated by Django 3.2.16 on 2023-01-16 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230111_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='description',
        ),
    ]
