# Generated by Django 3.2.16 on 2023-01-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_review_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='release_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
