# Generated by Django 3.2.16 on 2023-01-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_review_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
