# Generated by Django 3.2.16 on 2023-02-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20230202_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
